version: '3.8'
services:
  producer:
    build: ./data_ingestion
    container_name: wiretap-producer
    environment:
      - AUDIO-URL=/app/data
      - KAFKA-BOOTSTRAP=kafka:9092
    volumes:
      - ./data:/app/data
    depends_on:
      - kafka
    networks:
      - app-network

  consumer:
    build: ./data_transfer
    container_name: wiretap-consumer
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=audio_db
      - MONGO_COLLECTION=files
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=audio_index
      - HOSTILE_WORDS=/app/data/negative_keywords.txt
      - LESS_HOSTILE_WORDS=/app/data/neutral_keywords.txt
    volumes:
      - ./data:/app/data
    depends_on:
      - kafka
      - mongo
      - elasticsearch
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0 #
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

volumes:
  elasticsearch_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge